/*
 * Copyright 2016 github.com/straightway
 *
 *  Licensed under the Apache License, Version 2.0 (the &quot;License&quot;);
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an &quot;AS IS&quot; BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package straightway.testing

import org.junit.jupiter.api.Test

class GeneratedMethodDefaultTestsTest {

    data class TestClass(
            val string: String,
            val bool: Boolean,
            val char: Char,
            val byte: Byte,
            val short: Short,
            val int: Int,
            val long: Long,
            val float: Float,
            val double: Double,
            val nullablePrimitive: Int?
    ) {
        companion object {
            const val staticValue = "Static Value"
        }
    }

    @Test
    fun `testAutoGeneratedDataClassMethods succeeds for data class`() {
        val obj = TestClass("A", true, 'c', 2, 3, 5, 7, 11.0F, 13.0, 17)
        obj.testAutoGeneratedDataClassMethods()
    }

    @Test
    fun `testAutoGeneratedDataClassMethods fails for non data class`() {
        assertFails { "Non data class instance".testAutoGeneratedDataClassMethods() }
    }

    data class ClassWithPrivateField(private val privateField: Int)

    @Test
    fun `testAutoGeneratedDataClassMethods succeeds for data class with private field`() {
        ClassWithPrivateField(83).testAutoGeneratedDataClassMethods()
    }
}